name: Deploy CI
on: [push, pull_request]
jobs:
  deploy:
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        if: ${{ !env.VERCEL_TOKEN || !env.VERCEL_ORG_ID || !env.VERCEL_PROJECT_ID }}
        run: |
          exit 1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Get the production environment.env file
        if: ${{ secrets.ENV_PRODUCTION && github.ref_name == 'master' }}
        run: |
          cat > .env.production <<EOF
          ${{ secrets.ENV_PRODUCTION }}
          EOF

      - name: Deploy to Vercel Action(Production Environment)
        if: ${{ secrets.ENV_PRODUCTION && github.ref_name == 'master' }}
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          WORKING_DIRECTORY: ./
          GITHUB_DEPLOYMENT: false
          BUILD_ENV: |
            NODE_ENV=production 
            REACT_APP_ENV=pro 

      - name: Deploy to Vercel Action(Test Environment)
        if: ${{ github.ref_name == 'dev' }}
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          WORKING_DIRECTORY: ./
          GITHUB_DEPLOYMENT: false
          BUILD_ENV: |
            NODE_ENV=test 
            REACT_APP_ENV=test 

      - name: Deploy to Vercel Action(Development environment)
        if: ${{ github.ref_name != 'master' && github.ref_name != 'dev' }}
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          WORKING_DIRECTORY: ./
          GITHUB_DEPLOYMENT: false
          BUILD_ENV: |
            NODE_ENV=development 
            REACT_APP_ENV=dev 
